### ISSUE TITLE
Customize format

### ISSUE THREAD

**Issue by myroslambda** [phadej/cabal-fmt#11]
Hi,

We are cleaning many of our cabal files at Keera. We have some rules written down, but these are not the same as what cabal-fmt implements.

I see in the command line options that it is possible to customize the spacing. We'd also like to customize the order of the fields, at the top level and in each section.

I took a look in the code but, without being familiar with it, I could not see how to change it.

Any advice?

**Comment by phadej** [comment]
cabal-fmt doesn’t reorder fields; and I think it shouldn’t. Compare that with Haskell code formatter which would love definitions around.

The only thing moved to top is cabal-version, but with recent cabal-version values it’s required to be the first one; so it’s a special case

**Comment by myroslambda** [comment]
Thanks for the quick reply.

OK. The question for me still applies: I need to format a lot of cabal files. But I see how that might not helps others most.

1) If we were to add this, and I mean hard-coding a different order for now (not making it customizable, which would probably be much harder), is that something that could be done "easily" or would it require a lot of changes to cabal-fmt?

2) We have good reasons to want the fields to be in a specific order, and those could also apply to other projects. You say you think cabal-fmt shouldn't reorder fields. Could you elaborate?

**Comment by phadej** [comment]
Let me restart this.

I'm not against of ordering of fields as a general idea, but I don't think I'd enable that by default for everyone.

However if there would be some hard-coded ordering of fields, it will be "my" ordering, not yours. (I'm sorry, but description says *Tuned for Oleg's preference, but has some knobs still.*). So if you don't add knobs, the hard-coded order might change to something you don't like.

---

The configuration part is tricky.

Would a list of fields in preferred order be enough, with non-mentioned fields not sorted and pushed to the end, e.g. with `--sort-fields=foo,bar`

```cabal
xyz: ...
bar: ...
foo: ...
qqq: ...
```

would be resorted to

```cabal
foo: ...
bar: ...
xyz: ..
qqq: ...
```

?

How to deal with conditional sections? With `--sort-fields=default-language,build-depends`, I would **not like** the `exposed-modules` moved past the conditional in:

```cabal
default-language: Haskell2010
build-depends: base, containers

if os(windows)
  build-depends: Win32

exposed-modules: XYZ
```

I don't know answers to these questions. This is something I'd start with.

---

Alternatively there might be some algorithmic ordering (e.g. alphabetic), maybe you have some? Can these be composed (if people like some, but not other principles?)

---

Otherwise technically adding a sorting feature is not very difficult. There's `Refactoring` module, with a only one refactoring for now (the `expand` feature), but it takes a whole `.cabal` file structure, so ordering of fields should be possible. I'd split it into few modules:
- `Refactoring.Type` with type defs
- `Refactoring.ExpandExposedModules` with the current refactoring
- `Refactoring.*` other refactorings
- `Refactoring` re-exporting all of above

I'd appreciate if module reorganisation would be done first.

---

> We have good reasons to want the fields to be in a specific order

And these are? Concrete evidence is more convinvincing.

---

I think that in general it's difficult to come with a rule-set which is definitive.

Consider a haskell file:

```haskell
type C = (Comments, [Pragma])
type Refactoring             = forall r m. MonadCabalFmt r m => Refactoring' r m

refactoringExpandExposedModules :: Refactoring
refactoringExpandExposedModules = traverseFields refact where
  ...

traverseOf
    :: Applicative f
    => ((a -> f b) -> s ->  f t)
    -> (a -> f b) -> s ->  f t
traverseOf = id

_1 :: Functor f => (a -> f b) -> (a, c) -> f (b, c)
_1 f (a, c) = (\b -> (b, c)) <$> f a

traverseFields
    :: Applicative f
    => RefactoringOfField' r f
    -> [C.Field C] -> f [C.Field C]
traverseFields f = goMany where
    goMany = traverse go

    go (C.Field name fls)       = uncurry C.Field <$> f name fls
    go (C.Section name args fs) = C.Section name args <$> goMany fs
```

**none** of Haskell code formatters reorders these definitions, though one could agree e.g. to put `type` aliases on top (like it's already), or order definitions alphabetically (silly IMO, but for some reason Java class members are sometimes are ordered?).
`.cabal` fields is a bit different as there's finite set of possible fields, but not far off.

The next step from ordering fields is optional merging of them (e.g. `build-depends`), but e.g. I deliberately have separate ones (e.g GHC boot libs and others in https://hackage.haskell.org/package/these-1.0.1/these.cabal, I have different (though vague) policy for specifying lower bounds: GHC boot libs are "dictated" for what comes with GHC, for other libs it's freer). Slippery slope.

---

So to conclude: this seems difficult to make properly, so I defaulted to sorting fields manually for now.
Maybe it's only because I don't have strong principles figured out myself nor `cabal-fmt` (or something else) had various options to try out (i.e. to find out "what I like").

**Comment by myroslambda** [comment]
>  it will be "my" ordering, not yours.

That'd be fine: if an ordering is set, it probably wouldn't be too hard to change the code just in our branch to match our preferences. Not as ideal as being able to customize it, but we cannot expect you or anyone else to follow our layout rules.

> The configuration part is tricky.
>
> Would a list of fields in preferred order be enough

Probably. I'd suggest something like `--top-level-order=cabal-version,package-name,flags,...,libraries,executables,tests`, where some options match field names, and others match groups of sections. (I'm not arguing in favor of the flag name "top-level-order" itself.)

For sections with suboptions (e.g., libraries), perhaps something like `--in-section-order=exposed-modules,other-modules,...`.

Conditional blocks are hard to sort, because they can talk about many options. That's why we place them at the end, and sort the options within, but that could also be customized with `--conditionals-as-block` that determines if conditionals should be treated as one and be placed in one specific location, or be placed close to the options they configure.

> > We have good reasons to want the fields to be in a specific order
>
> And these are? Concrete evidence is more convinvincing.

We maintain a lot of packages, and we need to update cabal files often. This problem is not going away, so we try to make things we do repeatetedly as fast as we can.

Many changes to cabal files are very similar (and motivated by the same reason). While we cannot always do this with sed, we can easily do this by diffing the files (or with vi -d) and passing changes around.

Without giving too many details, we have defaulted to some order that follows:

- Top level info (package name and version are sort of the "module declaration" so they need to be the top; this block includes data files and extra source files), flags, libraries, executables, and tests.

- We normally put repo sources last because that's what cabal init used to do, but many people are putting these near the top and that's not necessarily bad, and it's related to `bug-reports`.

- For each section, we follow a top-down approach (interface first, low-level details second). This implies, for example, that exposed-modules goes before other-modules, which go before build-depends and cpp-options or ghc-options. Flags go last in each section, and the order of fields within flags follows the same rationale.

- Values for each option are given in new lines, except for the top global options and the flag declaration options (i.e., `default`, `manual`). This minimizes diffs. 

> none of Haskell code formatters reorders these definitions

You could order some definitions based on what interface is exported, and the internal dependencies between methods. However, to sort those blocks you still need some understanding of what the module does, which a formatter does not have.

Many people put types first, and API next, but not all might. But you wouldn't expect a code formatter for reorder public methods.

More related to the discussion regarding cabal fields and sections: you would not expect a cabal formatter to decide that a specific executable *must* appear before another executable. However, putting all libraries, e.g., before all tests, for example, is a choice that could make sense for many more users. It if can be customized, then all the better.

> I think that in general it's difficult to come with a rule-set which is definitive.

True. A discussion at this level tends to be expressed in terms of what people understand best, how "easy" it is to understand and maintain code, etc. All of these require extensive studies with hundreds or thousands of users to find any patterns that are generally better. That's complicated and expensive, and there's always someone who just wants to do things their way.

**Comment by myroslambda** [comment]
I just re-read my comment from before, and just wanted to clarify something. I said:

> If we were to add this, and I mean hard-coding a different order for now 

And you replied:

> However if there would be some hard-coded ordering of fields, it will be "my" ordering, not yours. 

When I said "we" in my sentence, I did not mean we as in "you and me", I meant we as in "my colleagues and me". The thought of imposing our formatting rules on this program, you or anyone else, never crossed my mind.

Sorry for the confusion.

**Comment by phadej** [comment]
I did small refactoring (mentioned in above comment) in https://github.com/phadej/cabal-fmt/pull/12, you could add your own refactoring if you will.

I'll be interested in seeing what you come up with, but cannot promise it will be merged as is.
